apiVersion: v1
kind: Service
metadata:
  name: third-eye-service
spec:
  externalTrafficPolicy: Local  # Preserves the client's IP
  selector:
    app: third-eye
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
      nodePort: 32008
  type: NodePort