apiVersion: v1
kind: Service
metadata:
  name: third-eye-service
spec:
  selector:
    app: third-eye
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 32000
  type: NodePort